name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build container
      run: ./_build_and_push.sh
      env:
        DH_USER: ${{ secrets.DH_USER }}
        DH_PASS: ${{ secrets.DH_PASS }}
